
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import ast.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class TestLangParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public TestLangParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public TestLangParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public TestLangParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\033\000\002\002\004\000\002\002\005\000\002\004" +
    "\002\000\002\004\007\000\002\004\010\000\002\003\002" +
    "\000\002\003\006\000\002\005\007\000\002\006\003\000" +
    "\002\006\004\000\002\007\005\000\002\007\010\000\002" +
    "\007\010\000\002\007\005\000\002\007\003\000\002\010" +
    "\003\000\002\010\004\000\002\011\007\000\002\011\007" +
    "\000\002\011\010\000\002\011\010\000\002\012\002\000" +
    "\002\012\006\000\002\013\007\000\002\013\007\000\002" +
    "\014\002\000\002\014\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\114\000\010\004\004\005\ufffc\027\ufffc\001\002\000" +
    "\004\017\103\001\002\000\004\002\102\001\002\000\006" +
    "\005\uffe8\027\uffe8\001\002\000\006\005\012\027\011\001" +
    "\002\000\006\005\uffe7\027\uffe7\001\002\000\004\015\074" +
    "\001\002\000\004\015\016\001\002\000\006\002\000\005" +
    "\012\001\002\000\006\002\ufff9\005\ufff9\001\002\000\006" +
    "\002\ufff8\005\ufff8\001\002\000\004\017\017\001\002\000" +
    "\014\006\023\010\020\011\027\012\026\013\025\001\002" +
    "\000\004\016\072\001\002\000\016\006\023\010\020\011" +
    "\027\012\026\013\025\020\071\001\002\000\016\006\ufff3" +
    "\010\ufff3\011\ufff3\012\ufff3\013\ufff3\020\ufff3\001\002\000" +
    "\010\022\050\024\051\025\052\001\002\000\016\006\ufff2" +
    "\010\ufff2\011\ufff2\012\ufff2\013\ufff2\020\ufff2\001\002\000" +
    "\004\016\046\001\002\000\004\016\041\001\002\000\004" +
    "\016\030\001\002\000\004\017\031\001\002\000\006\020" +
    "\uffec\024\032\001\002\000\004\023\036\001\002\000\004" +
    "\020\034\001\002\000\004\021\035\001\002\000\016\006" +
    "\ufff6\010\ufff6\011\ufff6\012\ufff6\013\ufff6\020\ufff6\001\002" +
    "\000\004\016\037\001\002\000\004\021\040\001\002\000" +
    "\004\020\uffeb\001\002\000\004\017\042\001\002\000\006" +
    "\020\uffec\024\032\001\002\000\004\020\044\001\002\000" +
    "\004\021\045\001\002\000\016\006\ufff5\010\ufff5\011\ufff5" +
    "\012\ufff5\013\ufff5\020\ufff5\001\002\000\004\021\047\001" +
    "\002\000\016\006\ufff4\010\ufff4\011\ufff4\012\ufff4\013\ufff4" +
    "\020\ufff4\001\002\000\004\023\065\001\002\000\004\026" +
    "\062\001\002\000\004\016\053\001\002\000\006\023\055" +
    "\026\054\001\002\000\004\016\060\001\002\000\004\016" +
    "\056\001\002\000\004\021\057\001\002\000\016\006\uffee" +
    "\010\uffee\011\uffee\012\uffee\013\uffee\020\uffee\001\002\000" +
    "\004\021\061\001\002\000\016\006\uffed\010\uffed\011\uffed" +
    "\012\uffed\013\uffed\020\uffed\001\002\000\004\016\063\001" +
    "\002\000\004\021\064\001\002\000\016\006\uffef\010\uffef" +
    "\011\uffef\012\uffef\013\uffef\020\uffef\001\002\000\004\014" +
    "\066\001\002\000\004\021\067\001\002\000\016\006\ufff0" +
    "\010\ufff0\011\ufff0\012\ufff0\013\ufff0\020\ufff0\001\002\000" +
    "\016\006\ufff1\010\ufff1\011\ufff1\012\ufff1\013\ufff1\020\ufff1" +
    "\001\002\000\006\002\ufffa\005\ufffa\001\002\000\004\021" +
    "\073\001\002\000\016\006\ufff7\010\ufff7\011\ufff7\012\ufff7" +
    "\013\ufff7\020\ufff7\001\002\000\004\023\075\001\002\000" +
    "\006\014\077\016\076\001\002\000\004\021\101\001\002" +
    "\000\004\021\100\001\002\000\006\005\uffe9\027\uffe9\001" +
    "\002\000\006\005\uffea\027\uffea\001\002\000\004\002\001" +
    "\001\002\000\010\007\uffff\020\uffff\025\uffff\001\002\000" +
    "\010\007\107\020\105\025\106\001\002\000\006\005\ufffb" +
    "\027\ufffb\001\002\000\004\016\113\001\002\000\004\023" +
    "\110\001\002\000\004\016\111\001\002\000\004\021\112" +
    "\001\002\000\010\007\ufffe\020\ufffe\025\ufffe\001\002\000" +
    "\004\023\114\001\002\000\004\016\115\001\002\000\004" +
    "\021\116\001\002\000\010\007\ufffd\020\ufffd\025\ufffd\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\114\000\006\002\004\003\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\014\006\001\001\000\010" +
    "\005\013\006\012\013\007\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\014\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\007\023\010\020\011\021\001\001\000\002\001\001" +
    "\000\006\007\067\011\021\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\032\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\012\042" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\103\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$TestLangParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$TestLangParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$TestLangParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  private Program program = new Program();
  
  public Program getProgram() {
    return program;
  }

  public void report_error(String message, Object info) {
    if (info == null) {
      System.err.println("Line ?: " + message);
      return;
    }
    Symbol s = (Symbol) info;
    int line = (s.left) + 1; 
    System.err.println("Line " + line + ": " + message);
  }
  
  public void report_fatal_error(String message, Object info) {
    report_error(message, info);
    System.exit(1);
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$TestLangParser$actions {
  private final TestLangParser parser;

  /** Constructor */
  CUP$TestLangParser$actions(TestLangParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$TestLangParser$do_action_part00000000(
    int                        CUP$TestLangParser$act_num,
    java_cup.runtime.lr_parser CUP$TestLangParser$parser,
    java.util.Stack            CUP$TestLangParser$stack,
    int                        CUP$TestLangParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$TestLangParser$result;

      /* select the action based on the action number */
      switch (CUP$TestLangParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		RESULT = start_val;
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$TestLangParser$parser.done_parsing();
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= config_block variable_list test_block_list 
            {
              Program RESULT =null;
		int cfgleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)).left;
		int cfgright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)).right;
		Config cfg = (Config)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)).value;
		int varsleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		Object vars = (Object)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		int testsleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).left;
		int testsright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).right;
		Object tests = (Object)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.peek()).value;
		 
      parser.program.setConfig(cfg);
      RESULT = parser.program;
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // config_items_list ::= 
            {
              Config RESULT =null;
		 
      RESULT = new Config();         // Step 1: Create empty Config
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("config_items_list",2, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // config_items_list ::= config_items_list BASE_URL EQUALS STRING SEMICOLON 
            {
              Config RESULT =null;
		int cfgleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)).left;
		int cfgright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)).right;
		Config cfg = (Config)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)).value;
		int urlleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int urlright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String url = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      cfg.setBaseUrl(url);           // Step 2: Add base_url to THIS Config
      RESULT = cfg;                  // Step 3: Return the updated Config
      //System.out.println("  🔗 base_url = " + url);
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("config_items_list",2, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // config_items_list ::= config_items_list HEADER STRING EQUALS STRING SEMICOLON 
            {
              Config RESULT =null;
		int cfgleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-5)).left;
		int cfgright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-5)).right;
		Config cfg = (Config)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-5)).value;
		int keyleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      cfg.addHeader(key, value);     // Step 2: Add header to THIS Config
      //System.out.println("  📋 header " + key + " = " + value);
      RESULT = cfg;                  // Step 3: Return the updated Config
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("config_items_list",2, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-5)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // config_block ::= 
            {
              Config RESULT =null;
		
      RESULT = null;
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("config_block",1, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // config_block ::= CONFIG LBRACE config_items_list RBRACE 
            {
              Config RESULT =null;
		int cfgleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int cfgright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		Config cfg = (Config)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		
      RESULT = cfg;  // Return the built Config
      //System.out.println("⚙️  Config: " + cfg);
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("config_block",1, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // test_block ::= TEST IDENTIFIER LBRACE statement_list RBRACE 
            {
              Test RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).value;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		List<Statement> stmts = (List<Statement>)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      RESULT = new Test(name, stmts);
      //System.out.println("🧪 Test: " + RESULT);
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("test_block",3, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // test_block_list ::= test_block 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).right;
		Test t = (Test)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.peek()).value;
		 
      parser.program.addTest(t);
      RESULT = null;  // Add this line
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("test_block_list",4, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // test_block_list ::= test_block_list test_block 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).right;
		Test t = (Test)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.peek()).value;
		 
      parser.program.addTest(t);
      RESULT = null;  // Add this line
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("test_block_list",4, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // statement ::= GET STRING SEMICOLON 
            {
              Statement RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      //System.out.println("  📡 GET " + path);
      RESULT = new Request(ast.HttpMethod.GET, path);
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // statement ::= POST STRING LBRACE request_body RBRACE SEMICOLON 
            {
              Statement RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)).right;
		String body = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)).value;
		 
      //System.out.println("  📡 POST " + path);
      Request req = new Request(ast.HttpMethod.POST, path);
      if (body != null) req.setBody(body);
      RESULT = req;
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-5)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // statement ::= PUT STRING LBRACE request_body RBRACE SEMICOLON 
            {
              Statement RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)).right;
		String body = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)).value;
		 
      //System.out.println("  📡 PUT " + path);
      Request req = new Request(ast.HttpMethod.PUT, path);
      if (body != null) req.setBody(body);
      RESULT = req;
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-5)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // statement ::= DELETE STRING SEMICOLON 
            {
              Statement RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      //System.out.println("  📡 DELETE " + path);
      RESULT = new Request(ast.HttpMethod.DELETE, path);
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-2)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // statement ::= assertion 
            {
              Statement RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).right;
		Assertion a = (Assertion)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.peek()).value;
		 
      RESULT = a;
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // statement_list ::= statement 
            {
              List<Statement> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.peek()).value;
		 
     //System.out.println("  → 1 statement parsed");
      List<Statement> list = new ArrayList<>();
      list.add(s);
      RESULT = list;
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("statement_list",6, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // statement_list ::= statement_list statement 
            {
              List<Statement> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		List<Statement> list = (List<Statement>)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.peek()).value;
		 
      //System.out.println("  → Another statement parsed");
      list.add(s);
      RESULT = list;
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("statement_list",6, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // assertion ::= EXPECT STATUS EQUALS NUMBER SEMICOLON 
            {
              Assertion RESULT =null;
		int codeleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int coderight = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String code = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      //System.out.println("  ✓ Expect status = " + code);
      RESULT = Assertion.status(Integer.parseInt(code));
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("assertion",7, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // assertion ::= EXPECT BODY CONTAINS STRING SEMICOLON 
            {
              Assertion RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int textright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      //System.out.println("  ✓ Expect body contains: " + text);
      RESULT = Assertion.bodyContains(text);
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("assertion",7, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // assertion ::= EXPECT HEADER STRING EQUALS STRING SEMICOLON 
            {
              Assertion RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      //System.out.println("  ✓ Expect header " + name + " = " + value);
      RESULT = Assertion.headerEquals(name, value);
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("assertion",7, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-5)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // assertion ::= EXPECT HEADER STRING CONTAINS STRING SEMICOLON 
            {
              Assertion RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).value;
		int substrleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int substrright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String substr = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      //System.out.println("  ✓ Expect header " + name + " contains: " + substr);
      RESULT = Assertion.headerContains(name, substr);
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("assertion",7, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-5)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // request_body ::= 
            {
              String RESULT =null;
		 
      //System.out.println("    (no req body)");
      RESULT = null;
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("request_body",8, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // request_body ::= BODY EQUALS STRING SEMICOLON 
            {
              String RESULT =null;
		int contentleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int contentright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String content = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      //System.out.println("    📄 body = " + content);
      RESULT = content;
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("request_body",8, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // variable_decl ::= LET IDENTIFIER EQUALS STRING SEMICOLON 
            {
              Variable RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      RESULT = new Variable(name, value);
      //System.out.println("📌 Variable: " + RESULT);
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("variable_decl",9, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // variable_decl ::= LET IDENTIFIER EQUALS NUMBER SEMICOLON 
            {
              Variable RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)).value;
		 
      RESULT = new Variable(name, value);
      //System.out.println("📌 Variable: " + RESULT);
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("variable_decl",9, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-4)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // variable_list ::= 
            {
              Object RESULT =null;
		 
      RESULT = null;  // Add this line
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("variable_list",10, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // variable_list ::= variable_list variable_decl 
            {
              Object RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()).right;
		Variable var = (Variable)((java_cup.runtime.Symbol) CUP$TestLangParser$stack.peek()).value;
		 
      parser.program.addVariable(var);
      RESULT = null;  // Add this line
    
              CUP$TestLangParser$result = parser.getSymbolFactory().newSymbol("variable_list",10, ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.elementAt(CUP$TestLangParser$top-1)), ((java_cup.runtime.Symbol)CUP$TestLangParser$stack.peek()), RESULT);
            }
          return CUP$TestLangParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$TestLangParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$TestLangParser$do_action(
    int                        CUP$TestLangParser$act_num,
    java_cup.runtime.lr_parser CUP$TestLangParser$parser,
    java.util.Stack            CUP$TestLangParser$stack,
    int                        CUP$TestLangParser$top)
    throws java.lang.Exception
    {
              return CUP$TestLangParser$do_action_part00000000(
                               CUP$TestLangParser$act_num,
                               CUP$TestLangParser$parser,
                               CUP$TestLangParser$stack,
                               CUP$TestLangParser$top);
    }
}

}
